Added Eslint and Prettier configuration
ritiksaxena124/nestjs-backend-template pull request #1
Opened 2024-10-07 09:45 UTC by ritiksaxena124

2024-10-07 09:46 UTC, ritiksaxena124 commented
If the configurations look good then we can add the husky to check for errors before every commit.

2024-10-07 09:59 UTC, abhykrss commented on .eslintrc.js
> +    'check-file/folder-naming-convention': ['error', { '**/*': 'KEBAB_CASE' }],
add check for 300 lines of code, excluding blank spaces and comments

2024-10-07 10:03 UTC, abhykrss commented on package.json
> +    "lint:fix": "eslint \"{src,test}/**/*.ts\" --fix",
Add a script called pre-commit-check  which will run prettier first then lint and if that pass, we commit.

2024-10-07 10:04 UTC, abhykrss commented on .eslintrc.js
> +    '@typescript-eslint/naming-convention': [
no console logs checks

2024-10-07 10:05 UTC, abhykrss commented on .eslintrc.js
>      '@typescript-eslint/interface-name-prefix': 'off',
no unused vars?

2024-10-07 10:05 UTC, abhykrss commented on .eslintrc.js
> +  ignorePatterns: ['.eslintrc.js', 'node_modules', 'dist', '.gitignore'],
no unused vars?

2024-10-07 10:06 UTC, abhykrss commented on .eslintrc.js
> +  ignorePatterns: ['.eslintrc.js', 'node_modules', 'dist', '.gitignore'],
enforce indentation of 2

2024-10-07 10:06 UTC, abhykrss commented on .eslintrc.js
> +  ignorePatterns: ['.eslintrc.js', 'node_modules', 'dist', '.gitignore'],
enforce eqeqeq (===)

2024-10-07 10:06 UTC, abhykrss commented on .eslintrc.js
> +  ignorePatterns: ['.eslintrc.js', 'node_modules', 'dist', '.gitignore'],
add  a rule that says if prettier not pass, lint will fail.

2024-10-07 10:07 UTC, abhykrss commented on .eslintrc.js
> +    '@typescript-eslint/naming-convention': [
duplicate imports and semi colons required

2024-10-07 10:08 UTC, abhykrss requested changes
changes requested

2024-10-07 10:27 UTC, ritiksaxena124 commented on .eslintrc.js
> +    '@typescript-eslint/naming-convention': [
> no console logs checks

ESLint should throw errors for every console or are we allowing `console.warn()`, `console.error()`

2024-10-07 10:48 UTC, abhykrss commented on .eslintrc.js
> +    '@typescript-eslint/naming-convention': [
console.anything not allowed if log is important, raise it using this.logger.warn("this is a warning")

2024-10-08 04:15 UTC, AjeetP-dev commented on .prettierrc
> +  "endOfLine": "auto"
validated

2024-10-08 04:16 UTC, merged